package com.data.tracer;

// Generated 15 Jun, 2015 3:57:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AttendanceDetails generated by hbm2java
 */
public class AttendanceDetails implements java.io.Serializable {

	private Long attendanceDetailsId;
	private UserDetails userDetails;
	private Date dateTime;
	private char status;
	private String userPhotoPath;
	private String lattitude;
	private String longitude;
	private String location;

	public AttendanceDetails() {
	}

	public AttendanceDetails(UserDetails userDetails, Date dateTime,
			char status, String userPhotoPath, String lattitude,
			String longitude) {
		this.userDetails = userDetails;
		this.dateTime = dateTime;
		this.status = status;
		this.userPhotoPath = userPhotoPath;
		this.lattitude = lattitude;
		this.longitude = longitude;
	}

	public AttendanceDetails(UserDetails userDetails, Date dateTime,
			char status, String userPhotoPath, String lattitude,
			String longitude, String location) {
		this.userDetails = userDetails;
		this.dateTime = dateTime;
		this.status = status;
		this.userPhotoPath = userPhotoPath;
		this.lattitude = lattitude;
		this.longitude = longitude;
		this.location = location;
	}

	public Long getAttendanceDetailsId() {
		return this.attendanceDetailsId;
	}

	public void setAttendanceDetailsId(Long attendanceDetailsId) {
		this.attendanceDetailsId = attendanceDetailsId;
	}

	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	public String getUserPhotoPath() {
		return this.userPhotoPath;
	}

	public void setUserPhotoPath(String userPhotoPath) {
		this.userPhotoPath = userPhotoPath;
	}

	public String getLattitude() {
		return this.lattitude;
	}

	public void setLattitude(String lattitude) {
		this.lattitude = lattitude;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

}
