package com.data.tracer;

// Generated 15 Jun, 2015 3:57:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BeatPlanDistributorAssignments generated by hbm2java
 */
public class BeatPlanDistributorAssignments implements java.io.Serializable {

	private Long bpDistAssignmentsId;
	private DistributorDetails distributorDetails;
	private BeatPlanDetails beatPlanDetails;
	private char status;
	private char visitFrequency;
	private Date dateTime;
	private Set<BeatPlanUserAssignments> beatPlanUserAssignmentses = new HashSet<BeatPlanUserAssignments>(
			0);

	public BeatPlanDistributorAssignments() {
	}

	public BeatPlanDistributorAssignments(
			DistributorDetails distributorDetails,
			BeatPlanDetails beatPlanDetails, char status, char visitFrequency,
			Date dateTime) {
		this.distributorDetails = distributorDetails;
		this.beatPlanDetails = beatPlanDetails;
		this.status = status;
		this.visitFrequency = visitFrequency;
		this.dateTime = dateTime;
	}

	public BeatPlanDistributorAssignments(
			DistributorDetails distributorDetails,
			BeatPlanDetails beatPlanDetails, char status, char visitFrequency,
			Date dateTime,
			Set<BeatPlanUserAssignments> beatPlanUserAssignmentses) {
		this.distributorDetails = distributorDetails;
		this.beatPlanDetails = beatPlanDetails;
		this.status = status;
		this.visitFrequency = visitFrequency;
		this.dateTime = dateTime;
		this.beatPlanUserAssignmentses = beatPlanUserAssignmentses;
	}

	public Long getBpDistAssignmentsId() {
		return this.bpDistAssignmentsId;
	}

	public void setBpDistAssignmentsId(Long bpDistAssignmentsId) {
		this.bpDistAssignmentsId = bpDistAssignmentsId;
	}

	public DistributorDetails getDistributorDetails() {
		return this.distributorDetails;
	}

	public void setDistributorDetails(DistributorDetails distributorDetails) {
		this.distributorDetails = distributorDetails;
	}

	public BeatPlanDetails getBeatPlanDetails() {
		return this.beatPlanDetails;
	}

	public void setBeatPlanDetails(BeatPlanDetails beatPlanDetails) {
		this.beatPlanDetails = beatPlanDetails;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	public char getVisitFrequency() {
		return this.visitFrequency;
	}

	public void setVisitFrequency(char visitFrequency) {
		this.visitFrequency = visitFrequency;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public Set<BeatPlanUserAssignments> getBeatPlanUserAssignmentses() {
		return this.beatPlanUserAssignmentses;
	}

	public void setBeatPlanUserAssignmentses(
			Set<BeatPlanUserAssignments> beatPlanUserAssignmentses) {
		this.beatPlanUserAssignmentses = beatPlanUserAssignmentses;
	}

}
