package com.data.tracer;

// Generated 15 Jun, 2015 3:57:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CafCollectionDetails generated by hbm2java
 */
public class CafCollectionDetails implements java.io.Serializable {

	private Long cafCollectionId;
	private RunnerVisitDetails runnerVisitDetails;
	private int totalCafCount;
	private int acceptedCafCount;
	private int rejectedCafCount;
	private int returnedCafCount;
	private String distributorPhotoPath;
	private String dstributorSignPath;
	private String runnerPhotoPath;
	private String cafProviderMobNum;
	private String remarks;
	private Date dateTime;

	public CafCollectionDetails() {
	}

	public CafCollectionDetails(RunnerVisitDetails runnerVisitDetails,
			int totalCafCount, int acceptedCafCount, int rejectedCafCount,
			int returnedCafCount, String distributorPhotoPath,
			String dstributorSignPath, String runnerPhotoPath,
			String cafProviderMobNum, Date dateTime) {
		this.runnerVisitDetails = runnerVisitDetails;
		this.totalCafCount = totalCafCount;
		this.acceptedCafCount = acceptedCafCount;
		this.rejectedCafCount = rejectedCafCount;
		this.returnedCafCount = returnedCafCount;
		this.distributorPhotoPath = distributorPhotoPath;
		this.dstributorSignPath = dstributorSignPath;
		this.runnerPhotoPath = runnerPhotoPath;
		this.cafProviderMobNum = cafProviderMobNum;
		this.dateTime = dateTime;
	}

	public CafCollectionDetails(RunnerVisitDetails runnerVisitDetails,
			int totalCafCount, int acceptedCafCount, int rejectedCafCount,
			int returnedCafCount, String distributorPhotoPath,
			String dstributorSignPath, String runnerPhotoPath,
			String cafProviderMobNum, String remarks, Date dateTime) {
		this.runnerVisitDetails = runnerVisitDetails;
		this.totalCafCount = totalCafCount;
		this.acceptedCafCount = acceptedCafCount;
		this.rejectedCafCount = rejectedCafCount;
		this.returnedCafCount = returnedCafCount;
		this.distributorPhotoPath = distributorPhotoPath;
		this.dstributorSignPath = dstributorSignPath;
		this.runnerPhotoPath = runnerPhotoPath;
		this.cafProviderMobNum = cafProviderMobNum;
		this.remarks = remarks;
		this.dateTime = dateTime;
	}

	public Long getCafCollectionId() {
		return this.cafCollectionId;
	}

	public void setCafCollectionId(Long cafCollectionId) {
		this.cafCollectionId = cafCollectionId;
	}

	public RunnerVisitDetails getRunnerVisitDetails() {
		return this.runnerVisitDetails;
	}

	public void setRunnerVisitDetails(RunnerVisitDetails runnerVisitDetails) {
		this.runnerVisitDetails = runnerVisitDetails;
	}

	public int getTotalCafCount() {
		return this.totalCafCount;
	}

	public void setTotalCafCount(int totalCafCount) {
		this.totalCafCount = totalCafCount;
	}

	public int getAcceptedCafCount() {
		return this.acceptedCafCount;
	}

	public void setAcceptedCafCount(int acceptedCafCount) {
		this.acceptedCafCount = acceptedCafCount;
	}

	public int getRejectedCafCount() {
		return this.rejectedCafCount;
	}

	public void setRejectedCafCount(int rejectedCafCount) {
		this.rejectedCafCount = rejectedCafCount;
	}

	public int getReturnedCafCount() {
		return this.returnedCafCount;
	}

	public void setReturnedCafCount(int returnedCafCount) {
		this.returnedCafCount = returnedCafCount;
	}

	public String getDistributorPhotoPath() {
		return this.distributorPhotoPath;
	}

	public void setDistributorPhotoPath(String distributorPhotoPath) {
		this.distributorPhotoPath = distributorPhotoPath;
	}

	public String getDstributorSignPath() {
		return this.dstributorSignPath;
	}

	public void setDstributorSignPath(String dstributorSignPath) {
		this.dstributorSignPath = dstributorSignPath;
	}

	public String getRunnerPhotoPath() {
		return this.runnerPhotoPath;
	}

	public void setRunnerPhotoPath(String runnerPhotoPath) {
		this.runnerPhotoPath = runnerPhotoPath;
	}

	public String getCafProviderMobNum() {
		return this.cafProviderMobNum;
	}

	public void setCafProviderMobNum(String cafProviderMobNum) {
		this.cafProviderMobNum = cafProviderMobNum;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

}
