package com.data.tracer;

// Generated 15 Jun, 2015 3:57:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * CafScanDetails generated by hbm2java
 */
public class CafScanDetails implements java.io.Serializable {

	private Long cafScanDetailsId;
	private long cafCollectionDetailsId;
	private String cafBarCode;
	private String cafScanImagePath;

	public CafScanDetails() {
	}

	public CafScanDetails(long cafCollectionDetailsId, String cafBarCode,
			String cafScanImagePath) {
		this.cafCollectionDetailsId = cafCollectionDetailsId;
		this.cafBarCode = cafBarCode;
		this.cafScanImagePath = cafScanImagePath;
	}

	public Long getCafScanDetailsId() {
		return this.cafScanDetailsId;
	}

	public void setCafScanDetailsId(Long cafScanDetailsId) {
		this.cafScanDetailsId = cafScanDetailsId;
	}

	public long getCafCollectionDetailsId() {
		return this.cafCollectionDetailsId;
	}

	public void setCafCollectionDetailsId(long cafCollectionDetailsId) {
		this.cafCollectionDetailsId = cafCollectionDetailsId;
	}

	public String getCafBarCode() {
		return this.cafBarCode;
	}

	public void setCafBarCode(String cafBarCode) {
		this.cafBarCode = cafBarCode;
	}

	public String getCafScanImagePath() {
		return this.cafScanImagePath;
	}

	public void setCafScanImagePath(String cafScanImagePath) {
		this.cafScanImagePath = cafScanImagePath;
	}

}
