package com.data.tracer;

// Generated 15 Jun, 2015 3:57:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CircleDetails generated by hbm2java
 */
public class CircleDetails implements java.io.Serializable {

	private Long circleId;
	private UserDetails userDetails;
	private String circleName;
	private String circleCode;
	private char status;
	private Date dateTime;
	private Set<RegionDetails> regionDetailses = new HashSet<RegionDetails>(0);
	private Set<UserToCircleDetails> userToCircleDetailses = new HashSet<UserToCircleDetails>(
			0);

	public CircleDetails() {
	}

	public CircleDetails(UserDetails userDetails, String circleName,
			String circleCode, char status, Date dateTime) {
		this.userDetails = userDetails;
		this.circleName = circleName;
		this.circleCode = circleCode;
		this.status = status;
		this.dateTime = dateTime;
	}

	public CircleDetails(UserDetails userDetails, String circleName,
			String circleCode, char status, Date dateTime,
			Set<RegionDetails> regionDetailses,
			Set<UserToCircleDetails> userToCircleDetailses) {
		this.userDetails = userDetails;
		this.circleName = circleName;
		this.circleCode = circleCode;
		this.status = status;
		this.dateTime = dateTime;
		this.regionDetailses = regionDetailses;
		this.userToCircleDetailses = userToCircleDetailses;
	}

	public Long getCircleId() {
		return this.circleId;
	}

	public void setCircleId(Long circleId) {
		this.circleId = circleId;
	}

	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	public String getCircleName() {
		return this.circleName;
	}

	public void setCircleName(String circleName) {
		this.circleName = circleName;
	}

	public String getCircleCode() {
		return this.circleCode;
	}

	public void setCircleCode(String circleCode) {
		this.circleCode = circleCode;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public Set<RegionDetails> getRegionDetailses() {
		return this.regionDetailses;
	}

	public void setRegionDetailses(Set<RegionDetails> regionDetailses) {
		this.regionDetailses = regionDetailses;
	}

	public Set<UserToCircleDetails> getUserToCircleDetailses() {
		return this.userToCircleDetailses;
	}

	public void setUserToCircleDetailses(
			Set<UserToCircleDetails> userToCircleDetailses) {
		this.userToCircleDetailses = userToCircleDetailses;
	}

}
