package com.data.tracer;

// Generated 15 Jun, 2015 3:57:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * DashboardDetails generated by hbm2java
 */
public class DashboardDetails implements java.io.Serializable {

	private Long dashboardDetailsId;
	private UserDetails userDetails;
	private char status;
	private char attendanceReport;
	private char visitsVsBeatPlanReport;
	private char nonPerformedRunnersReport;
	private char topRunnersReport;
	private char topDistributorsReport;
	private char topRegionsReport;
	private char topZonesReport;
	private char topHubsReport;

	public DashboardDetails() {
	}

	public DashboardDetails(UserDetails userDetails, char status,
			char attendanceReport, char visitsVsBeatPlanReport,
			char nonPerformedRunnersReport, char topRunnersReport,
			char topDistributorsReport, char topRegionsReport,
			char topZonesReport, char topHubsReport) {
		this.userDetails = userDetails;
		this.status = status;
		this.attendanceReport = attendanceReport;
		this.visitsVsBeatPlanReport = visitsVsBeatPlanReport;
		this.nonPerformedRunnersReport = nonPerformedRunnersReport;
		this.topRunnersReport = topRunnersReport;
		this.topDistributorsReport = topDistributorsReport;
		this.topRegionsReport = topRegionsReport;
		this.topZonesReport = topZonesReport;
		this.topHubsReport = topHubsReport;
	}

	public Long getDashboardDetailsId() {
		return this.dashboardDetailsId;
	}

	public void setDashboardDetailsId(Long dashboardDetailsId) {
		this.dashboardDetailsId = dashboardDetailsId;
	}

	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	public char getAttendanceReport() {
		return this.attendanceReport;
	}

	public void setAttendanceReport(char attendanceReport) {
		this.attendanceReport = attendanceReport;
	}

	public char getVisitsVsBeatPlanReport() {
		return this.visitsVsBeatPlanReport;
	}

	public void setVisitsVsBeatPlanReport(char visitsVsBeatPlanReport) {
		this.visitsVsBeatPlanReport = visitsVsBeatPlanReport;
	}

	public char getNonPerformedRunnersReport() {
		return this.nonPerformedRunnersReport;
	}

	public void setNonPerformedRunnersReport(char nonPerformedRunnersReport) {
		this.nonPerformedRunnersReport = nonPerformedRunnersReport;
	}

	public char getTopRunnersReport() {
		return this.topRunnersReport;
	}

	public void setTopRunnersReport(char topRunnersReport) {
		this.topRunnersReport = topRunnersReport;
	}

	public char getTopDistributorsReport() {
		return this.topDistributorsReport;
	}

	public void setTopDistributorsReport(char topDistributorsReport) {
		this.topDistributorsReport = topDistributorsReport;
	}

	public char getTopRegionsReport() {
		return this.topRegionsReport;
	}

	public void setTopRegionsReport(char topRegionsReport) {
		this.topRegionsReport = topRegionsReport;
	}

	public char getTopZonesReport() {
		return this.topZonesReport;
	}

	public void setTopZonesReport(char topZonesReport) {
		this.topZonesReport = topZonesReport;
	}

	public char getTopHubsReport() {
		return this.topHubsReport;
	}

	public void setTopHubsReport(char topHubsReport) {
		this.topHubsReport = topHubsReport;
	}

}
