package com.data.tracer;

// Generated 15 Jun, 2015 3:57:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RunnerVisittedLocationDetails generated by hbm2java
 */
public class RunnerVisittedLocationDetails implements java.io.Serializable {

	private Long runnerVisittedLocationId;
	private UserDetails userDetails;
	private String lattitude;
	private String longitude;
	private String location;
	private Date dateTime;

	public RunnerVisittedLocationDetails() {
	}

	public RunnerVisittedLocationDetails(UserDetails userDetails,
			String lattitude, String longitude, String location, Date dateTime) {
		this.userDetails = userDetails;
		this.lattitude = lattitude;
		this.longitude = longitude;
		this.location = location;
		this.dateTime = dateTime;
	}

	public Long getRunnerVisittedLocationId() {
		return this.runnerVisittedLocationId;
	}

	public void setRunnerVisittedLocationId(Long runnerVisittedLocationId) {
		this.runnerVisittedLocationId = runnerVisittedLocationId;
	}

	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	public String getLattitude() {
		return this.lattitude;
	}

	public void setLattitude(String lattitude) {
		this.lattitude = lattitude;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

}
