package com.data.tracer;

// Generated 15 Jun, 2015 3:57:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RunnerOfflineVisitDetails generated by hbm2java
 */
public class RunnerOfflineVisitDetails implements java.io.Serializable {

	private Long runnerOfflineVisitId;
	private String offlineVisitCode;
	private String distributorCode;
	private String beatPlanCode;
	private String runnerCode;
	private char status;
	private Date visitTimeStamp;

	public RunnerOfflineVisitDetails() {
	}

	public RunnerOfflineVisitDetails(String offlineVisitCode,
			String distributorCode, String beatPlanCode, String runnerCode,
			char status, Date visitTimeStamp) {
		this.offlineVisitCode = offlineVisitCode;
		this.distributorCode = distributorCode;
		this.beatPlanCode = beatPlanCode;
		this.runnerCode = runnerCode;
		this.status = status;
		this.visitTimeStamp = visitTimeStamp;
	}

	public Long getRunnerOfflineVisitId() {
		return this.runnerOfflineVisitId;
	}

	public void setRunnerOfflineVisitId(Long runnerOfflineVisitId) {
		this.runnerOfflineVisitId = runnerOfflineVisitId;
	}

	public String getOfflineVisitCode() {
		return this.offlineVisitCode;
	}

	public void setOfflineVisitCode(String offlineVisitCode) {
		this.offlineVisitCode = offlineVisitCode;
	}

	public String getDistributorCode() {
		return this.distributorCode;
	}

	public void setDistributorCode(String distributorCode) {
		this.distributorCode = distributorCode;
	}

	public String getBeatPlanCode() {
		return this.beatPlanCode;
	}

	public void setBeatPlanCode(String beatPlanCode) {
		this.beatPlanCode = beatPlanCode;
	}

	public String getRunnerCode() {
		return this.runnerCode;
	}

	public void setRunnerCode(String runnerCode) {
		this.runnerCode = runnerCode;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	public Date getVisitTimeStamp() {
		return this.visitTimeStamp;
	}

	public void setVisitTimeStamp(Date visitTimeStamp) {
		this.visitTimeStamp = visitTimeStamp;
	}

}
