package com.data.tracer;

// Generated 15 Jun, 2015 3:57:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RunnerVisitDetails generated by hbm2java
 */
public class RunnerVisitDetails implements java.io.Serializable {

	private Long runnerVisitId;
	private BeatPlanUserAssignments beatPlanUserAssignments;
	private char visitNo;
	private Date visitTimeStamp;
	private char status;
	private Set<CafCollectionDetails> cafCollectionDetailses = new HashSet<CafCollectionDetails>(
			0);

	public RunnerVisitDetails() {
	}

	public RunnerVisitDetails(BeatPlanUserAssignments beatPlanUserAssignments,
			char visitNo, Date visitTimeStamp, char status) {
		this.beatPlanUserAssignments = beatPlanUserAssignments;
		this.visitNo = visitNo;
		this.visitTimeStamp = visitTimeStamp;
		this.status = status;
	}

	public RunnerVisitDetails(BeatPlanUserAssignments beatPlanUserAssignments,
			char visitNo, Date visitTimeStamp, char status,
			Set<CafCollectionDetails> cafCollectionDetailses) {
		this.beatPlanUserAssignments = beatPlanUserAssignments;
		this.visitNo = visitNo;
		this.visitTimeStamp = visitTimeStamp;
		this.status = status;
		this.cafCollectionDetailses = cafCollectionDetailses;
	}

	public Long getRunnerVisitId() {
		return this.runnerVisitId;
	}

	public void setRunnerVisitId(Long runnerVisitId) {
		this.runnerVisitId = runnerVisitId;
	}

	public BeatPlanUserAssignments getBeatPlanUserAssignments() {
		return this.beatPlanUserAssignments;
	}

	public void setBeatPlanUserAssignments(
			BeatPlanUserAssignments beatPlanUserAssignments) {
		this.beatPlanUserAssignments = beatPlanUserAssignments;
	}

	public char getVisitNo() {
		return this.visitNo;
	}

	public void setVisitNo(char visitNo) {
		this.visitNo = visitNo;
	}

	public Date getVisitTimeStamp() {
		return this.visitTimeStamp;
	}

	public void setVisitTimeStamp(Date visitTimeStamp) {
		this.visitTimeStamp = visitTimeStamp;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	public Set<CafCollectionDetails> getCafCollectionDetailses() {
		return this.cafCollectionDetailses;
	}

	public void setCafCollectionDetailses(
			Set<CafCollectionDetails> cafCollectionDetailses) {
		this.cafCollectionDetailses = cafCollectionDetailses;
	}

}
