package com.data.tracer;

// Generated 15 Jun, 2015 3:57:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * SmsCategoryDetails generated by hbm2java
 */
public class SmsCategoryDetails implements java.io.Serializable {

	private Long smsCategoryId;
	private String smsCategoryName;
	private char status;
	private Set<SmsTemplateDetails> smsTemplateDetailses = new HashSet<SmsTemplateDetails>(
			0);

	public SmsCategoryDetails() {
	}

	public SmsCategoryDetails(String smsCategoryName, char status) {
		this.smsCategoryName = smsCategoryName;
		this.status = status;
	}

	public SmsCategoryDetails(String smsCategoryName, char status,
			Set<SmsTemplateDetails> smsTemplateDetailses) {
		this.smsCategoryName = smsCategoryName;
		this.status = status;
		this.smsTemplateDetailses = smsTemplateDetailses;
	}

	public Long getSmsCategoryId() {
		return this.smsCategoryId;
	}

	public void setSmsCategoryId(Long smsCategoryId) {
		this.smsCategoryId = smsCategoryId;
	}

	public String getSmsCategoryName() {
		return this.smsCategoryName;
	}

	public void setSmsCategoryName(String smsCategoryName) {
		this.smsCategoryName = smsCategoryName;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	public Set<SmsTemplateDetails> getSmsTemplateDetailses() {
		return this.smsTemplateDetailses;
	}

	public void setSmsTemplateDetailses(
			Set<SmsTemplateDetails> smsTemplateDetailses) {
		this.smsTemplateDetailses = smsTemplateDetailses;
	}

}
