package com.data.tracer;

// Generated 15 Jun, 2015 3:57:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UploadedCafDetails generated by hbm2java
 */
public class UploadedCafDetails implements java.io.Serializable {

	private long uploadCafDetailsId;
	private DistributorDetails distributorDetails;
	private String mobileNo;
	private String orderNumber;
	private String subAgentCode;
	private String cafType;
	private String connectionStatus;
	private char cafStatus;
	private char status;
	private Date dateTime;

	public UploadedCafDetails() {
	}

	public UploadedCafDetails(long uploadCafDetailsId,
			DistributorDetails distributorDetails, String mobileNo,
			String orderNumber, char cafStatus, char status, Date dateTime) {
		this.uploadCafDetailsId = uploadCafDetailsId;
		this.distributorDetails = distributorDetails;
		this.mobileNo = mobileNo;
		this.orderNumber = orderNumber;
		this.cafStatus = cafStatus;
		this.status = status;
		this.dateTime = dateTime;
	}

	public UploadedCafDetails(long uploadCafDetailsId,
			DistributorDetails distributorDetails, String mobileNo,
			String orderNumber, String subAgentCode, String cafType,
			String connectionStatus, char cafStatus, char status, Date dateTime) {
		this.uploadCafDetailsId = uploadCafDetailsId;
		this.distributorDetails = distributorDetails;
		this.mobileNo = mobileNo;
		this.orderNumber = orderNumber;
		this.subAgentCode = subAgentCode;
		this.cafType = cafType;
		this.connectionStatus = connectionStatus;
		this.cafStatus = cafStatus;
		this.status = status;
		this.dateTime = dateTime;
	}

	public long getUploadCafDetailsId() {
		return this.uploadCafDetailsId;
	}

	public void setUploadCafDetailsId(long uploadCafDetailsId) {
		this.uploadCafDetailsId = uploadCafDetailsId;
	}

	public DistributorDetails getDistributorDetails() {
		return this.distributorDetails;
	}

	public void setDistributorDetails(DistributorDetails distributorDetails) {
		this.distributorDetails = distributorDetails;
	}

	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	public String getSubAgentCode() {
		return this.subAgentCode;
	}

	public void setSubAgentCode(String subAgentCode) {
		this.subAgentCode = subAgentCode;
	}

	public String getCafType() {
		return this.cafType;
	}

	public void setCafType(String cafType) {
		this.cafType = cafType;
	}

	public String getConnectionStatus() {
		return this.connectionStatus;
	}

	public void setConnectionStatus(String connectionStatus) {
		this.connectionStatus = connectionStatus;
	}

	public char getCafStatus() {
		return this.cafStatus;
	}

	public void setCafStatus(char cafStatus) {
		this.cafStatus = cafStatus;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

}
