package com.data.tracer;

// Generated 15 Jun, 2015 3:57:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserToHubDetails generated by hbm2java
 */
public class UserToHubDetails implements java.io.Serializable {

	private Long userToHubDetailsId;
	private HubDetails hubDetails;
	private UserDetails userDetails;
	private char status;

	public UserToHubDetails() {
	}

	public UserToHubDetails(HubDetails hubDetails, UserDetails userDetails,
			char status) {
		this.hubDetails = hubDetails;
		this.userDetails = userDetails;
		this.status = status;
	}

	public Long getUserToHubDetailsId() {
		return this.userToHubDetailsId;
	}

	public void setUserToHubDetailsId(Long userToHubDetailsId) {
		this.userToHubDetailsId = userToHubDetailsId;
	}

	public HubDetails getHubDetails() {
		return this.hubDetails;
	}

	public void setHubDetails(HubDetails hubDetails) {
		this.hubDetails = hubDetails;
	}

	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

}
