package com.data.tracer;

// Generated 15 Jun, 2015 3:57:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserToZoneDetails generated by hbm2java
 */
public class UserToZoneDetails implements java.io.Serializable {

	private Long userToZoneDetailsId;
	private UserDetails userDetails;
	private ZoneDetails zoneDetails;
	private char status;

	public UserToZoneDetails() {
	}

	public UserToZoneDetails(UserDetails userDetails, ZoneDetails zoneDetails,
			char status) {
		this.userDetails = userDetails;
		this.zoneDetails = zoneDetails;
		this.status = status;
	}

	public Long getUserToZoneDetailsId() {
		return this.userToZoneDetailsId;
	}

	public void setUserToZoneDetailsId(Long userToZoneDetailsId) {
		this.userToZoneDetailsId = userToZoneDetailsId;
	}

	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	public ZoneDetails getZoneDetails() {
		return this.zoneDetails;
	}

	public void setZoneDetails(ZoneDetails zoneDetails) {
		this.zoneDetails = zoneDetails;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

}
