package com.data.tracer;

// Generated 15 Jun, 2015 3:57:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserToCircleDetails generated by hbm2java
 */
public class UserToCircleDetails implements java.io.Serializable {

	private Long userToCircleDetailsId;
	private UserDetails userDetails;
	private CircleDetails circleDetails;
	private char status;

	public UserToCircleDetails() {
	}

	public UserToCircleDetails(UserDetails userDetails,
			CircleDetails circleDetails, char status) {
		this.userDetails = userDetails;
		this.circleDetails = circleDetails;
		this.status = status;
	}

	public Long getUserToCircleDetailsId() {
		return this.userToCircleDetailsId;
	}

	public void setUserToCircleDetailsId(Long userToCircleDetailsId) {
		this.userToCircleDetailsId = userToCircleDetailsId;
	}

	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	public CircleDetails getCircleDetails() {
		return this.circleDetails;
	}

	public void setCircleDetails(CircleDetails circleDetails) {
		this.circleDetails = circleDetails;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

}
