package com.data.tracer;

// Generated 15 Jun, 2015 3:57:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserAuthCodeDetails generated by hbm2java
 */
public class UserAuthCodeDetails implements java.io.Serializable {

	private Long userAuthCodeId;
	private UserDetails userDetails;
	private String authCode;
	private Date loginTimestamp;
	private Date logoutTimestamp;
	private char status;

	public UserAuthCodeDetails() {
	}

	public UserAuthCodeDetails(UserDetails userDetails, String authCode,
			Date loginTimestamp, char status) {
		this.userDetails = userDetails;
		this.authCode = authCode;
		this.loginTimestamp = loginTimestamp;
		this.status = status;
	}

	public UserAuthCodeDetails(UserDetails userDetails, String authCode,
			Date loginTimestamp, Date logoutTimestamp, char status) {
		this.userDetails = userDetails;
		this.authCode = authCode;
		this.loginTimestamp = loginTimestamp;
		this.logoutTimestamp = logoutTimestamp;
		this.status = status;
	}

	public Long getUserAuthCodeId() {
		return this.userAuthCodeId;
	}

	public void setUserAuthCodeId(Long userAuthCodeId) {
		this.userAuthCodeId = userAuthCodeId;
	}

	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	public String getAuthCode() {
		return this.authCode;
	}

	public void setAuthCode(String authCode) {
		this.authCode = authCode;
	}

	public Date getLoginTimestamp() {
		return this.loginTimestamp;
	}

	public void setLoginTimestamp(Date loginTimestamp) {
		this.loginTimestamp = loginTimestamp;
	}

	public Date getLogoutTimestamp() {
		return this.logoutTimestamp;
	}

	public void setLogoutTimestamp(Date logoutTimestamp) {
		this.logoutTimestamp = logoutTimestamp;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

}
