package com.data.tracer;

// Generated 15 Jun, 2015 3:57:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserPasswordHistoryDetails generated by hbm2java
 */
public class UserPasswordHistoryDetails implements java.io.Serializable {

	private Long userPasswordHistoryDetailsId;
	private UserDetails userDetails;
	private String password;

	public UserPasswordHistoryDetails() {
	}

	public UserPasswordHistoryDetails(UserDetails userDetails, String password) {
		this.userDetails = userDetails;
		this.password = password;
	}

	public Long getUserPasswordHistoryDetailsId() {
		return this.userPasswordHistoryDetailsId;
	}

	public void setUserPasswordHistoryDetailsId(
			Long userPasswordHistoryDetailsId) {
		this.userPasswordHistoryDetailsId = userPasswordHistoryDetailsId;
	}

	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
