package com.data.tracer;

// Generated 15 Jun, 2015 3:57:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserDetails generated by hbm2java
 */
public class UserDetails implements java.io.Serializable {

	private Long userId;
	private RoleDetails roleDetails;
	private String userCode;
	private String userName;
	private String password;
	private String lastName;
	private String name;
	private char gender;
	private Date dateOfBirth;
	private Character maritalStatus;
	private String bloodGroup;
	private Date dateOfAnniversary;
	private String address;
	private String city;
	private String state;
	private String district;
	private String country;
	private String pinCode;
	private String photoPath;
	private String primaryContactNo;
	private String primaryEmail;
	private String secondaryContactNo;
	private String secondaryEmail;
	private char status;
	private Date dateTime;
	private String imeiNo;
	private String officePhone;
	private String nearestPoliceStation;
	private Set<UserToCircleDetails> userToCircleDetailses = new HashSet<UserToCircleDetails>(
			0);
	private Set<DashboardDetails> dashboardDetailses = new HashSet<DashboardDetails>(
			0);
	private Set<RunnerVisittedLocationDetails> runnerVisittedLocationDetailses = new HashSet<RunnerVisittedLocationDetails>(
			0);
	private Set<UserToZoneDetails> userToZoneDetailses = new HashSet<UserToZoneDetails>(
			0);
	private Set<UserPasswordHistoryDetails> userPasswordHistoryDetailses = new HashSet<UserPasswordHistoryDetails>(
			0);
	private Set<SmsTemplateDetails> smsTemplateDetailses = new HashSet<SmsTemplateDetails>(
			0);
	private Set<UserAuthCodeDetails> userAuthCodeDetailses = new HashSet<UserAuthCodeDetails>(
			0);
	private Set<BeatPlanUserAssignments> beatPlanUserAssignmentses = new HashSet<BeatPlanUserAssignments>(
			0);
	private Set<ZoneDetails> zoneDetailses = new HashSet<ZoneDetails>(0);
	private Set<UserToHubDetails> userToHubDetailses = new HashSet<UserToHubDetails>(
			0);
	private Set<CircleDetails> circleDetailses = new HashSet<CircleDetails>(0);
	private Set<UserToRegionDetails> userToRegionDetailses = new HashSet<UserToRegionDetails>(
			0);
	private Set<UserReportingToDetails> userReportingToDetailses = new HashSet<UserReportingToDetails>(
			0);
	private Set<BeatPlanDetails> beatPlanDetailses = new HashSet<BeatPlanDetails>(
			0);
	private Set<HubDetails> hubDetailses = new HashSet<HubDetails>(0);
	private Set<DistributorDetails> distributorDetailses = new HashSet<DistributorDetails>(
			0);
	private Set<RegionDetails> regionDetailses = new HashSet<RegionDetails>(0);
	private Set<AttendanceDetails> attendanceDetailses = new HashSet<AttendanceDetails>(
			0);

	public UserDetails() {
	}

	public UserDetails(RoleDetails roleDetails, String userCode,
			String userName, String password, String lastName, String name,
			char gender, Date dateOfBirth, String address,
			String primaryContactNo, String primaryEmail, char status,
			Date dateTime) {
		this.roleDetails = roleDetails;
		this.userCode = userCode;
		this.userName = userName;
		this.password = password;
		this.lastName = lastName;
		this.name = name;
		this.gender = gender;
		this.dateOfBirth = dateOfBirth;
		this.address = address;
		this.primaryContactNo = primaryContactNo;
		this.primaryEmail = primaryEmail;
		this.status = status;
		this.dateTime = dateTime;
	}

	public UserDetails(RoleDetails roleDetails, String userCode,
			String userName, String password, String lastName, String name,
			char gender, Date dateOfBirth, Character maritalStatus,
			String bloodGroup, Date dateOfAnniversary, String address,
			String city, String state, String district, String country,
			String pinCode, String photoPath, String primaryContactNo,
			String primaryEmail, String secondaryContactNo,
			String secondaryEmail, char status, Date dateTime, String imeiNo,
			String officePhone, String nearestPoliceStation,
			Set<UserToCircleDetails> userToCircleDetailses,
			Set<DashboardDetails> dashboardDetailses,
			Set<RunnerVisittedLocationDetails> runnerVisittedLocationDetailses,
			Set<UserToZoneDetails> userToZoneDetailses,
			Set<UserPasswordHistoryDetails> userPasswordHistoryDetailses,
			Set<SmsTemplateDetails> smsTemplateDetailses,
			Set<UserAuthCodeDetails> userAuthCodeDetailses,
			Set<BeatPlanUserAssignments> beatPlanUserAssignmentses,
			Set<ZoneDetails> zoneDetailses,
			Set<UserToHubDetails> userToHubDetailses,
			Set<CircleDetails> circleDetailses,
			Set<UserToRegionDetails> userToRegionDetailses,
			Set<UserReportingToDetails> userReportingToDetailses,
			Set<BeatPlanDetails> beatPlanDetailses,
			Set<HubDetails> hubDetailses,
			Set<DistributorDetails> distributorDetailses,
			Set<RegionDetails> regionDetailses,
			Set<AttendanceDetails> attendanceDetailses) {
		this.roleDetails = roleDetails;
		this.userCode = userCode;
		this.userName = userName;
		this.password = password;
		this.lastName = lastName;
		this.name = name;
		this.gender = gender;
		this.dateOfBirth = dateOfBirth;
		this.maritalStatus = maritalStatus;
		this.bloodGroup = bloodGroup;
		this.dateOfAnniversary = dateOfAnniversary;
		this.address = address;
		this.city = city;
		this.state = state;
		this.district = district;
		this.country = country;
		this.pinCode = pinCode;
		this.photoPath = photoPath;
		this.primaryContactNo = primaryContactNo;
		this.primaryEmail = primaryEmail;
		this.secondaryContactNo = secondaryContactNo;
		this.secondaryEmail = secondaryEmail;
		this.status = status;
		this.dateTime = dateTime;
		this.imeiNo = imeiNo;
		this.officePhone = officePhone;
		this.nearestPoliceStation = nearestPoliceStation;
		this.userToCircleDetailses = userToCircleDetailses;
		this.dashboardDetailses = dashboardDetailses;
		this.runnerVisittedLocationDetailses = runnerVisittedLocationDetailses;
		this.userToZoneDetailses = userToZoneDetailses;
		this.userPasswordHistoryDetailses = userPasswordHistoryDetailses;
		this.smsTemplateDetailses = smsTemplateDetailses;
		this.userAuthCodeDetailses = userAuthCodeDetailses;
		this.beatPlanUserAssignmentses = beatPlanUserAssignmentses;
		this.zoneDetailses = zoneDetailses;
		this.userToHubDetailses = userToHubDetailses;
		this.circleDetailses = circleDetailses;
		this.userToRegionDetailses = userToRegionDetailses;
		this.userReportingToDetailses = userReportingToDetailses;
		this.beatPlanDetailses = beatPlanDetailses;
		this.hubDetailses = hubDetailses;
		this.distributorDetailses = distributorDetailses;
		this.regionDetailses = regionDetailses;
		this.attendanceDetailses = attendanceDetailses;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public RoleDetails getRoleDetails() {
		return this.roleDetails;
	}

	public void setRoleDetails(RoleDetails roleDetails) {
		this.roleDetails = roleDetails;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public char getGender() {
		return this.gender;
	}

	public void setGender(char gender) {
		this.gender = gender;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public Character getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(Character maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	public String getBloodGroup() {
		return this.bloodGroup;
	}

	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	public Date getDateOfAnniversary() {
		return this.dateOfAnniversary;
	}

	public void setDateOfAnniversary(Date dateOfAnniversary) {
		this.dateOfAnniversary = dateOfAnniversary;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getPinCode() {
		return this.pinCode;
	}

	public void setPinCode(String pinCode) {
		this.pinCode = pinCode;
	}

	public String getPhotoPath() {
		return this.photoPath;
	}

	public void setPhotoPath(String photoPath) {
		this.photoPath = photoPath;
	}

	public String getPrimaryContactNo() {
		return this.primaryContactNo;
	}

	public void setPrimaryContactNo(String primaryContactNo) {
		this.primaryContactNo = primaryContactNo;
	}

	public String getPrimaryEmail() {
		return this.primaryEmail;
	}

	public void setPrimaryEmail(String primaryEmail) {
		this.primaryEmail = primaryEmail;
	}

	public String getSecondaryContactNo() {
		return this.secondaryContactNo;
	}

	public void setSecondaryContactNo(String secondaryContactNo) {
		this.secondaryContactNo = secondaryContactNo;
	}

	public String getSecondaryEmail() {
		return this.secondaryEmail;
	}

	public void setSecondaryEmail(String secondaryEmail) {
		this.secondaryEmail = secondaryEmail;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public String getImeiNo() {
		return this.imeiNo;
	}

	public void setImeiNo(String imeiNo) {
		this.imeiNo = imeiNo;
	}

	public String getOfficePhone() {
		return this.officePhone;
	}

	public void setOfficePhone(String officePhone) {
		this.officePhone = officePhone;
	}

	public String getNearestPoliceStation() {
		return this.nearestPoliceStation;
	}

	public void setNearestPoliceStation(String nearestPoliceStation) {
		this.nearestPoliceStation = nearestPoliceStation;
	}

	public Set<UserToCircleDetails> getUserToCircleDetailses() {
		return this.userToCircleDetailses;
	}

	public void setUserToCircleDetailses(
			Set<UserToCircleDetails> userToCircleDetailses) {
		this.userToCircleDetailses = userToCircleDetailses;
	}

	public Set<DashboardDetails> getDashboardDetailses() {
		return this.dashboardDetailses;
	}

	public void setDashboardDetailses(Set<DashboardDetails> dashboardDetailses) {
		this.dashboardDetailses = dashboardDetailses;
	}

	public Set<RunnerVisittedLocationDetails> getRunnerVisittedLocationDetailses() {
		return this.runnerVisittedLocationDetailses;
	}

	public void setRunnerVisittedLocationDetailses(
			Set<RunnerVisittedLocationDetails> runnerVisittedLocationDetailses) {
		this.runnerVisittedLocationDetailses = runnerVisittedLocationDetailses;
	}

	public Set<UserToZoneDetails> getUserToZoneDetailses() {
		return this.userToZoneDetailses;
	}

	public void setUserToZoneDetailses(
			Set<UserToZoneDetails> userToZoneDetailses) {
		this.userToZoneDetailses = userToZoneDetailses;
	}

	public Set<UserPasswordHistoryDetails> getUserPasswordHistoryDetailses() {
		return this.userPasswordHistoryDetailses;
	}

	public void setUserPasswordHistoryDetailses(
			Set<UserPasswordHistoryDetails> userPasswordHistoryDetailses) {
		this.userPasswordHistoryDetailses = userPasswordHistoryDetailses;
	}

	public Set<SmsTemplateDetails> getSmsTemplateDetailses() {
		return this.smsTemplateDetailses;
	}

	public void setSmsTemplateDetailses(
			Set<SmsTemplateDetails> smsTemplateDetailses) {
		this.smsTemplateDetailses = smsTemplateDetailses;
	}

	public Set<UserAuthCodeDetails> getUserAuthCodeDetailses() {
		return this.userAuthCodeDetailses;
	}

	public void setUserAuthCodeDetailses(
			Set<UserAuthCodeDetails> userAuthCodeDetailses) {
		this.userAuthCodeDetailses = userAuthCodeDetailses;
	}

	public Set<BeatPlanUserAssignments> getBeatPlanUserAssignmentses() {
		return this.beatPlanUserAssignmentses;
	}

	public void setBeatPlanUserAssignmentses(
			Set<BeatPlanUserAssignments> beatPlanUserAssignmentses) {
		this.beatPlanUserAssignmentses = beatPlanUserAssignmentses;
	}

	public Set<ZoneDetails> getZoneDetailses() {
		return this.zoneDetailses;
	}

	public void setZoneDetailses(Set<ZoneDetails> zoneDetailses) {
		this.zoneDetailses = zoneDetailses;
	}

	public Set<UserToHubDetails> getUserToHubDetailses() {
		return this.userToHubDetailses;
	}

	public void setUserToHubDetailses(Set<UserToHubDetails> userToHubDetailses) {
		this.userToHubDetailses = userToHubDetailses;
	}

	public Set<CircleDetails> getCircleDetailses() {
		return this.circleDetailses;
	}

	public void setCircleDetailses(Set<CircleDetails> circleDetailses) {
		this.circleDetailses = circleDetailses;
	}

	public Set<UserToRegionDetails> getUserToRegionDetailses() {
		return this.userToRegionDetailses;
	}

	public void setUserToRegionDetailses(
			Set<UserToRegionDetails> userToRegionDetailses) {
		this.userToRegionDetailses = userToRegionDetailses;
	}

	public Set<UserReportingToDetails> getUserReportingToDetailses() {
		return this.userReportingToDetailses;
	}

	public void setUserReportingToDetailses(
			Set<UserReportingToDetails> userReportingToDetailses) {
		this.userReportingToDetailses = userReportingToDetailses;
	}

	public Set<BeatPlanDetails> getBeatPlanDetailses() {
		return this.beatPlanDetailses;
	}

	public void setBeatPlanDetailses(Set<BeatPlanDetails> beatPlanDetailses) {
		this.beatPlanDetailses = beatPlanDetailses;
	}

	public Set<HubDetails> getHubDetailses() {
		return this.hubDetailses;
	}

	public void setHubDetailses(Set<HubDetails> hubDetailses) {
		this.hubDetailses = hubDetailses;
	}

	public Set<DistributorDetails> getDistributorDetailses() {
		return this.distributorDetailses;
	}

	public void setDistributorDetailses(
			Set<DistributorDetails> distributorDetailses) {
		this.distributorDetailses = distributorDetailses;
	}

	public Set<RegionDetails> getRegionDetailses() {
		return this.regionDetailses;
	}

	public void setRegionDetailses(Set<RegionDetails> regionDetailses) {
		this.regionDetailses = regionDetailses;
	}

	public Set<AttendanceDetails> getAttendanceDetailses() {
		return this.attendanceDetailses;
	}

	public void setAttendanceDetailses(
			Set<AttendanceDetails> attendanceDetailses) {
		this.attendanceDetailses = attendanceDetailses;
	}

}
