package com.tracer.dao.model;




/**
 * UserPasswordHistoryDetails generated by hbm2java
 */
public class UserPasswordHistoryDetails implements java.io.Serializable {
	private static final long serialVersionUID = 8444083742227068273L;
	private Long userPasswordHistoryDetailsId;
	private UserDetails userDetails;
	private String password;

	public UserPasswordHistoryDetails() {
	}

	public UserPasswordHistoryDetails(UserDetails userDetails, String password
			) {
		this.userDetails = userDetails;
		this.password = password;
	}

	public Long getUserPasswordHistoryDetailsId() {
		return this.userPasswordHistoryDetailsId;
	}

	public void setUserPasswordHistoryDetailsId(
			Long userPasswordHistoryDetailsId) {
		this.userPasswordHistoryDetailsId = userPasswordHistoryDetailsId;
	}

	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	


}
